### ISSUE TITLE
JS error on http://surveyjs.org/builder/ Cannot read property 'isJsonCorrect' of undefined

### ISSUE THREAD

**Issue by vangorra** [andrewtelnov/surveyjs.editor#12]
Using Chrome for Linux Version 52.0.2743.116 (64-bit)

1. goto http://surveyjs.org/builder/
2. Optionally add less than 3 tools from the toolbox. (Adding 3 or more prevents the error from occurring)
3. click on the "JSON Editor" tab.
4. click on "Designer" tab.

You should see this error:
`
editor.ts:279 Uncaught TypeError: Cannot read property 'isJsonCorrect' of undefined
`

Confirmed this also occurs with version 0.9.10 from npm.

**Comment by andrewtelnov** [comment]
I have just tried it with Chrome exactly the same version, running on Ubuntu. I was not able to reproduce the problem. However, several days ago, a guy wrote me about the similar issue under Windows 7. 
Probably there are some additional steps. I believe this is the line that shows error: 
`if (!this.textWorker.isJsonCorrect)`
and` this.textWorker` is undefined in your case. However, I do not see, how it can be null or undefined :-(

Could you go a little deeper and debug a little? I just need more tips. I want to fix the issue.

Thank you,
Andrew

**Comment by vangorra** [comment]
Full stacktrace for the error:
```
editor.ts:279 Uncaught TypeError: Cannot read property 'isJsonCorrect' of undefined
SurveyEditor.canSwitchViewType @ editor.ts:279
SurveyEditor.showDesigner @ editor.ts:287
SurveyEditor.selectDesignerClick @ editor.ts:100
(anonymous function) @ knockout.js:89
dispatch @ jquery.js:4435
r.handle @ jquery.js:4121
```

In doing some debugging, sometimes, processJson() is being called after canSwitchViewType(). Seems to me processJson() should be getting called first. 

Further testings shows that if I click on "JSON Editor" immediately after the page loads and then immediately click on "Designer", I can get the error to reproduce on my Chromebook Pixel and Ubuntu Chrome browser. Haven't tried windows.

**Comment by andrewtelnov** [comment]
Thank you very much for the information.
I do not know what is going on exactly, Probably, ace editor is creating later in some version of Chromes and cause issues.
Anyway, I have made several changes. Could you please try it out now? I have updated: http://surveyjs.org/builder/

Thank you,
Andrew

**Comment by vangorra** [comment]
I can no longer reproduce the issue on either machine I was using. Seems fixed to me.

**Comment by andrewtelnov** [comment]
Great!
Thanks  a lot for reporting the issue and providing the detailed information.

Thank you,
Andrew
