### ISSUE TITLE
Unable to set the same value for "Value" and "Text" in Choices Property

### ISSUE THREAD

**Issue by DimitriFreimann** [andrewtelnov/surveyjs.editor#14]
If i want to set the same value for "Value" and "Text" in Choices property for a question, the text vanished when I leave the question. Is there any possibility to fix this?

**Comment by andrewtelnov** [comment]
Hi @DimitriFreimann from v0.9.12 I remove the text if it equals to the value. For example:
{value: 1, text: 'one'} will store both value and text, but { value: 1, text: '1'} will store the value only.
Are you talking about this issue or do I miss anything?

Thank you,
Andrew

**Comment by DimitriFreimann** [comment]
Hi Andrew, this is exactly the „issue“. We need something like {value: one, text}, but there is a {one} only for the question. We need this, to analyze it on our server. So we need always the same structure.

Thank you,
Dimitri

Von: Andrew [mailto:notifications@github.com]
Gesendet: Donnerstag, 29. September 2016 09:28
An: andrewtelnov/surveyjs.editor <surveyjs.editor@noreply.github.com>
Cc: Freimann, Dimitri <dimitri.freimann@bechtle.com>; Mention <mention@noreply.github.com>
Betreff: Re: [andrewtelnov/surveyjs.editor] Unable to set the same value for "Value" and "Text" in Choices Property (#14)


Hi @DimitriFreimann<https://github.com/DimitriFreimann> from v0.9.12 I remove the text if it equals to the value. For example:
{value: 1, text: 'one'} will store both value and text, but { value: 1, text: '1'} will store the value only.
Are you talking about this issue or do I miss anything?

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@DimitriFreimann I got you. To me it sounds like an option. I will add this option to the next minor release.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@DimitriFreimann I have added this functionality, please create the editor using the following code:
`var editor = new SurveyEditor.SurveyEditor("editorContainer", { alwaySaveTextInPropertyEditors : false});`

**Comment by DimitriFreimann** [comment]
You’re great! Thank you!

Von: Andrew [mailto:notifications@github.com]
Gesendet: Montag, 10. Oktober 2016 10:52
An: andrewtelnov/surveyjs.editor <surveyjs.editor@noreply.github.com>
Cc: Freimann, Dimitri <dimitri.freimann@bechtle.com>; Mention <mention@noreply.github.com>
Betreff: Re: [andrewtelnov/surveyjs.editor] Unable to set the same value for "Value" and "Text" in Choices Property (#14)


@DimitriFreimann<https://github.com/DimitriFreimann> I have added this functionality, please create the editor using the following code:
var editor = new SurveyEditor.SurveyEditor("editorContainer", { alwaySaveTextInPropertyEditors : false});
