### ISSUE TITLE
Matrix (dynamic rows) & Matrix (multiple choice) not working

### ISSUE THREAD

**Issue by kailashyadav** [andrewtelnov/surveyjs.editor#16]
@andrewtelnov if i try to add these type of question, i get following error and question doesn't come up unless another type of question is created.

`knockout.js:72 Uncaught ReferenceError: Unable to process binding "template: function (){return { name:'propertyeditor-itemvalues',data:choicesEditor} }"`
`Message: Unable to process binding "template: function (){return { name:'propertyeditor-modal',data:$data} }"`
`Message: Unable to process binding "text: function (){return koText }"`
`Message: koText is not defined`

**Comment by andrewtelnov** [comment]
Yes, thank you! I have fixed the bug-

**Comment by kailashyadav** [comment]
@andrewtelnov Have you released the latest version? I am using it in one of my production application.

**Comment by andrewtelnov** [comment]
@kailashyadav I have updated websites and zip file that you may download. However, I do not update NPM package.

**Comment by myselflokendra** [comment]
@andrewtelnov : When can we have that in NPM package, as I am working on top of your builder to add few more questions and properties to it, however, it starts breaking this one, if you just let me know the fixes to be done here, I can build by my own.

**Comment by myselflokendra** [comment]
@andrewtelnov : My bad, i have not taken latest from upstream, please ignore.
