### ISSUE TITLE
Manual choises rrder

### ISSUE THREAD

**Issue by randall84** [andrewtelnov/surveyjs.editor#21]
A nice feature would be to be able to choose the order of "choices".
Now I can set it with choicesOrder, but just "ASC, DESC, RANDOM"

What do you think about it?
thanks

**Comment by andrewtelnov** [comment]
Hi @randall84, could you please describe in more details. I am not sure I follow you :-(

**Comment by randall84** [comment]
In questions where I have "multiple choices" I cannot set the orders of the Answers(maybe with drag & drop?)

![screen shot 2016-11-14 at 15 53 19](https://cloud.githubusercontent.com/assets/5146354/20269207/8d45203e-aa82-11e6-9fc0-6596f893c1c6.png)

**Comment by andrewtelnov** [comment]
@randall84, totally agreed. It makes the perfect sense.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
Please refer to this issue: https://github.com/andrewtelnov/surveyjs.editor/issues/23

**Comment by randall84** [comment]
thanks!
