### ISSUE TITLE
Survey editor build process fails

### ISSUE THREAD

**Issue by Teqa** [andrewtelnov/surveyjs.editor#3]
When running a gulp makedist, errors appear on namespaces. 

$ gulp makedist
[08:39:57] Warning: gulp version mismatch:
[08:39:57] Global gulp is 3.9.1
[08:39:57] Local gulp is 3.9.0
[08:39:59] Using gulpfile C:\www\git\survey.js.editor\gulpfile.js
[08:39:59] Starting 'makedist'...
[08:39:59] Starting 'templates'...
[08:39:59] Finished 'templates' after 13 ms
[08:39:59] Starting 'typescript:sources'...
[08:39:59] Starting 'typescript:tests'...
[08:39:59] Starting 'test:copy-index-html'...
[08:39:59] Finished 'test:copy-index-html' after 451 μs
[08:39:59] Starting 'sass'...
[08:39:59] Finished 'sass' after 2.55 ms
C:/www/git/survey.js.editor/src/dragdrophelper.ts(7,34): error TS2503: Cannot find namespace 'Survey'.
C:/www/git/survey.js.editor/src/dragdrophelper.ts(9,30): error TS2503: Cannot find namespace 'Survey'.
C:/www/git/survey.js.editor/src/dragdrophelper.ts(9,54): error TS2503: Cannot find namespace 'Survey'.
C:/www/git/survey.js.editor/src/dragdrophelper.ts(24,59): error TS2503: Cannot find namespace 'Survey'.
C:/www/git/survey.js.editor/src/dragdrophelper.ts(30,51): error TS2503: Cannot find namespace 'Survey'.
C:/www/git/survey.js.editor/src/dragdrophelper.ts(43,34): error TS2304: Cannot find name 'Survey'.
C:/www/git/survey.js.editor/src/dragdrophelper.ts(44,21): error TS2304: Cannot find name 'Survey'.
C:/www/git/survey.js.editor/src/dragdrophelper.ts(48,35): error TS2503: Cannot find namespace 'Survey'.
C:/www/git/survey.js.editor/src/dragdrophelper.ts(51,34): error TS2304: Cannot find name 'Survey'.
C:/www/git/survey.js.editor/src/dragdrophelper.ts(56,62): error TS2503: Cannot find namespace 'Survey'.
C:/www/git/survey.js.editor/src/dragdrophelper.ts(69,57): error TS2503: Cannot find namespace 'Survey'.
C:/www/git/survey.js.editor/src/dragdrophelper.ts(82,48): error TS2503: Cannot find namespace 'Survey'.

**Comment by andrewtelnov** [comment]
Yes, I will deal with it. I will put the instruction and add npm package.
It is in the top of my Todo list.

**Comment by andrewtelnov** [comment]
FYI: I have corrected the scripts. 
As soon as my pull request will be accepted (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/9053), I will finish the task.

**Comment by Teqa** [comment]
Hi Andrew, 
What is your status on the build script?
The linked pull request was closed?
