### ISSUE TITLE
Npm package surveyjs-editor package.json file contains a wrong main path

### ISSUE THREAD

**Issue by xaviertremblay** [andrewtelnov/surveyjs.editor#34]
It should be ./dist/surveyeditor.min.js instead of  ./js/surveyeditor.min.js

The folder has only dist when loaded from npm.

![editor](https://cloud.githubusercontent.com/assets/13556543/21434958/0825a58c-c845-11e6-9377-9f2603035fac.png)

**Comment by andrewtelnov** [comment]
@xaviertremblay Yes, thank you. I was going to publish a new version into npm and I have fixed this issue.
