### ISSUE TITLE
Uncaught TypeError: k.SurveyTemplateText is not a constructor

### ISSUE THREAD

**Issue by SlowburnAZ** [andrewtelnov/surveyjs.editor#37]
@andrewtelnov 
I'm getting this error simply by including the survey and survey editor code in my page.

Anyone else experiencing this?

**Comment by SlowburnAZ** [comment]
Okay, I must be out my mind today.

I had the jQuery version of the survey code, but the builder is supporting only Knockout at this time.  I switched to the KO version of the survey code, and all is good.

My bad.

**Comment by dmitrykurmanov** [comment]
@SlowburnAZ, we implemented angular2 and jQuery versions.

**Comment by andrewtelnov** [comment]
@dmitrykurmanov,  @SlowburnAZ is talking about the SurveyJS Editor. Editor supports knockout at the current moment.
