### ISSUE TITLE
Build file gives TypeError

### ISSUE THREAD

**Issue by Teqa** [andrewtelnov/surveyjs.editor#5]
When processing the build for the editor, running the editor gives an error:

`TypeError: $root.getLocString is not a function
	

...{with($data||{}){return{'css':function(){return {active:koIsShowDesigner()} }}}

	`

Running the editor via the download file is ok. So technically the latest version seems to work fine, but the build is not getting at the same result. 
Did we miss a step, i.e. adding a localization file?
I see this in the surveyjs project, but not in the editor.

**Comment by andrewtelnov** [comment]
It is totally my fault. Locally, I use the local version of surveyjs. The build uses the npm version of surveyjs. 
I have to change the way I develope the surveyjs.editor. Use surveyjs npm version only, or publish all projects to npm at once. 
I have updated all projects in NPM to 0.9.5. It should be fine now.

Thank you,
Andrew

**Comment by Teqa** [comment]
Issue is actually still there. Updated git and reran 
gulp makedist
copied js from package folder.

**Comment by andrewtelnov** [comment]
You are using the old surveyed file. 
Please update  survey.bootstrap.js. I have tried - everything is fine now.

**Comment by andrewtelnov** [comment]
Do not forget to call
 npm install
To get survey-knockout-bootstrap v0.9.5

**Comment by Teqa** [comment]
Have done the npm install, but do not get the other statement:
"Please update survey.bootstrap.js. I"
Which file is this?

**Comment by andrewtelnov** [comment]
Sorry, for not being clear: surveyeditor.js depends on survey.bootstrap.js. You should use v0.9.5, in the header: * surveyjs - Survey JavaScript library v0.9.5.
This version contains method: SurveyModel.prototype.getLocString
You have error because you are using the old version of survey.bootstrap.js, likely version 0.9.3. It doesn't have this method.

Thank you,
Andrew
